namespace TP.Sound {

    public enum SoundID {
        None = 0,

        // BGM
        A,
        B,
        C,
        D,
        bgm01,
        bgm02,
        bgm03,
        bgm04,
        bgm05,
        bgm07,
        bgm08,
        bgm09,
        bgm10,
        bgm11,
        bgm12,
        bgm13,
        bgm14,
        bgm15,
        bgm18,
        bgm19,
        bgm20,

        // SFX
        bonesetting,
        city_streets,
        door_open,
        footstep,
        grenade_bomb,
        gulp,
        hatch_open,
        hit,
        hungry,
        nature_sound_birds,
        nature_sound_bug,
        ppsh41_shot,
        ppsh_41_shot,
        radio_sound,
        receiver,
        shell_reload,
        shooting,
        speaker,
        sticky,
        tank_engine,
        tank_fire_shot,
        tank_hit,
        tank_track,
        tank_track_1,
        tokarev_shot,
        tokarev_shot_1,
        weapons_reload,
        weapons_reload_1,
        weapons_use
    }
}